### ISSUE TITLE
Bioconductor devel / multiple methods tables found for ‘aperm’

### ISSUE THREAD

**Issue by bbimber** [Bioconductor/DelayedArray#102]
Hello,

We have R code that indirectly depends on DelayedArray and we have tests that run against the bioconductor devel branch. I realize devel isnt stable, but we just started getting warnings like: "multiple methods tables found for ‘aperm’", which fail R CMD CHECK. There seem to be recent commits here around that aperm, so I thought I'd report this in case there is anything to look at. If you'd like me to post more detail on this let me know.

**Comment by hpages** [comment]
Ah.. it seems that I forgot to bump **DelayedArray**'s version when I moved the `aperm()` S4 generic from **DelayedArray** to **BiocGenerics** a few days ago :confused:  As a consequence I guess you still have the "old" **DelayedArray** (version 0.23.1) with the `aperm()` S4 generic in it but you have the new version of **BiocGenerics** (0.43.4) which also defines the `aperm()` S4 generic.

I just bumped **DelayedArray** version to 0.23.2. This new version should become available via `BiocManager::install()` in BioC devel in the next 24-48 hours or so.

Cheers,
H.
