### ISSUE TITLE
`set_grid_context()` changed in `RELEASE_3_17`

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/DelayedArray#104]
d2e1862f5c933b27d21e116d4e3da1a3b9ac6bec introduces a new argument, `current_viewport`, which breaks `beachmat::colBlockApply()`, which in turn breaks a whole bunch of other downstream packages. Seems like this change could have waited in BioC-devel for a bit longer, or at least a no-op default for `current_viewport=` could have been added.

**Comment by hpages** [comment]
oops, sorry for that. I meant to make this new argument optional. Will be fixed in a few minutes.

**Comment by hpages** [comment]
Done.

In release: 00e36c7e92e2e814517014d510701577155f7933
In devel: 8f1387004145e8a4f91a918281ef05acb2da6b25

We normally don't run the daily builds on Saturdays but I'm going to make an exception for the 3.17 builds, so we get **DelayedArray** 0.26.6 out there as soon as possible.
 
Sorry again for the trouble.
