### ISSUE TITLE
Failed to install geneLenDataBase

### ISSUE THREAD

**Issue by fhao2** [Bioconductor/DelayedArray#118]
I tried to install package "geneLenDataBase" to run ChAMP. I kept getting message 
"Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'DelayedArray' 0.24.0 is being loaded, but >= 0.27.1 is required
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'geneLenDataBase'". 

But my DelayedArray is in version 0.30. I used to remove the package and re-install, which did not work.

**Comment by lshep** [comment]
Can you please share your `sessionInfo()`

**Comment by fhao2** [comment]
Sure,

R version 4.4.1 Patched (2024-07-31 r86969 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

**Comment by lshep** [comment]
Can you provide the full `sessionInfo()` that includes not only that information but all the loaded packages/version after trying the install/load of the package.  It would also be helpful to show your install commands with full output as well.  It looks like you also posted on the Support Site;  as suggested there trying a `BiocManager::valid` and `BiocManager:install` to make sure all packages are up-to-date might also help.

**Comment by fhao2** [comment]
Here is the session info

```
R version 4.4.1 Patched (2024-07-31 r86969 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.23 compiler_4.4.1      tools_4.4.1         fs_1.6.4 
```
And this is the output when I tried to install geneLenDataBase

```
> BiocManager::install("geneLenDataBase")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.19 (BiocManager 1.30.23), R 4.4.1 Patched (2024-07-31 r86969
  ucrt)
Installing package(s) 'geneLenDataBase'
Install source package 'geneLenDataBase'

Try to open URL’https://bioconductor.org/packages/3.19/data/experiment/src/contrib/geneLenDataBase_1.40.1.tar.gz'
Content type 'application/x-gzip' length 100438279 bytes (95.8 MB)
downloaded 95.8 MB

* installing *source* package 'geneLenDataBase' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Warning: multiple methods tables found for 'sort'
Warning: multiple methods tables found for 'sort'
Warning: multiple methods tables found for 'sort'
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'DelayedArray' 0.24.0 is being loaded, but >= 0.27.1 is required
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'geneLenDataBase'
```

**Comment by hpages** [comment]
It seems that maybe you have more than one installation of **DelayedArray**, This can happen if you use more than one package installation path. What's the output of `.libPaths()`?

**Comment by hpages** [comment]
Were you able to solve this @fhao2 ?
