### ISSUE TITLE
Support `finite` argument in `range,DelayedArray-method`

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/DelayedArray#18]
Is it possible to add the `finite` argument to mimic the `range.default` S3 method?

**Comment by hpages** [comment]
Hi Pete,

This is implemented in DelayedArray 0.7.12. See commit ce0eaf047fece32379275cddf55ff3bec99571b1

H.

**Comment by PeteHaitch** [comment]
Thanks!
