### ISSUE TITLE
registering `SerialParam()` sets a global preference, but package-specific preference required

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/DelayedArray#28]
This line https://github.com/Bioconductor/DelayedArray/blob/master/R/zzz.R#L12 sets a global preference for SerialParam() on Windows -- whenever DelayedArray is loaded, the users' preference is replaced by `SerialParam()` for all uses of DelayedArray. But really one wants only a package-local preference, maybe through a helper function invoked on each use of `bplapply()` and friends. Maybe I gave misleading advice earlier.

The current implementation causes windows builds in both release and devel to fail, e.g., http://bioconductor.org/checkResults/devel/bioc-LATEST/BiocParallel/tokay1-checksrc.html when, in the example before the failing example, GenomicAlignments depends on DelayedArray, replacing the normal default (SnowParam()) with SerialParam().

**Comment by hpages** [comment]
Thanks for the report. With the following change https://github.com/Bioconductor/DelayedArray/commit/28630a034f1be6ec5d44561f3daaa49b404e23ed , hopefully DelayedArray will be a better citizen. 

BTW the link you provided to the code in DelayedArray is not pointing to the right line anymore. Did you use a permalink for this?

**Comment by mtmorgan** [comment]
didn't know about permalinks, thanks!

**Comment by hpages** [comment]
Closing this. Feel free to re-open if this is not properly addressed.

**Comment by hpages** [comment]
Oops, I just realized today that BiocParallel is also currently failing in Bioc 3.7 on Windows because of this problem:

    https://bioconductor.org/checkResults/3.7/bioc-LATEST/BiocParallel/tokay2-checksrc.html

I just backported the https://github.com/Bioconductor/DelayedArray/commit/28630a034f1be6ec5d44561f3daaa49b404e23ed fix to the RELEASE_3_7 branch of DelayedArray (version 0.6.6). This should clear the BiocParallel CHECK error on Windows in the next 24-48 hours.
