### ISSUE TITLE
Mention need for 'matrixClass' in 'Implementing a backend' vignette

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/DelayedArray#3]
This isn't currently documented in the 'Implementing a backend' vignette, but I think this is necessary. [E.g., from HDF5Array](https://github.com/Bioconductor/HDF5Array/blob/bd5760cf874415efef34834f2846931d9bbe76ac/R/HDF5Array-class.R#L131-L132)
```
### For internal use only.
setMethod("matrixClass", "HDF5Array", function(x) "HDF5Matrix")
```

**Comment by hpages** [comment]
It is indeed necessary. I added it to DelayedArray 0.5.6. Thanks for spotting this!
