### ISSUE TITLE
unable to change dim

### ISSUE THREAD

**Issue by mikejiang** [Bioconductor/DelayedArray#30]
I am trying to adapt the in-memory-matrix code to support `DelayedArray`, but run into the following error when it tries to coerce `2d` matrix to `3d` array
```r
> a <- array(runif(10), dim=c(2, 5))
> A <- DelayedArray(a)
> dim(a) <- c(dim(a), 1)
> a
, , 1

          [,1]      [,2]      [,3]      [,4]       [,5]
[1,] 0.8584375 0.3051332 0.5198660 0.1106134 0.87002666
[2,] 0.4446721 0.6195048 0.3658824 0.1589915 0.01943329

> dim(A) <- c(dim(A), 1)
Error in .normalize_dim_replacement_value(value, x_dim) : 
  too many dimensions supplied
> packageVersion("DelayedArray")
[1] ‘0.7.41’
```

**Comment by hpages** [comment]
Ah, perfect! DelayedArray objects didn't support this so far and I was thinking in adding it. It's on the TODO list (https://github.com/Bioconductor/DelayedArray/blob/998fa6af9f1f9ff78691ce00ae8cab0a3542f32a/TODO#L14-L16). I think it should be easy. Great that you have a use case. I'll try to have this ready today or tomorrow.

**Comment by mikejiang** [comment]
Great!

**Comment by hpages** [comment]
This should work with DelayedArray 0.7.42:
https://github.com/Bioconductor/DelayedArray/commit/b8a6103fe81a5df04b57887d44bffcce33d9f43c
Note that, unlike with an ordinary array, the are still restrictions w.r.t. what the `dim()` setter can do on a DelayedArray object `x`. For example if `dim(x)` is `c(5, 4)` you can't do `dim(x) <- c(10, 2)`. However you can change the order of the dims with `aperm()` (generalized transposition).

**Comment by mikejiang** [comment]
Nice! Thanks a lot.
