### ISSUE TITLE
names on dimnames

### ISSUE THREAD

**Issue by lawremi** [Bioconductor/DelayedArray#43]
Names on dimnames seem to be dropped. Those are sometimes useful for indicating what the names mean.

```
dn <- dimnames(array)
names(dn) <- c("foo", "bar")
dimnames(array) <- dn
names(dimnames(array)) # NULL
```

**Comment by hpages** [comment]
Hi Michael, this should be addressed in DelayedArray 0.11.8.

H.

**Comment by hpages** [comment]
I actually had to commit one more tweak to properly support names on the dimnames (commit fc32d0792129ea50158dfe17a34924364bf4b60e). Hopefully this time I got it right.

**Comment by lawremi** [comment]
Thanks a lot, @hpages !
