### ISSUE TITLE
`is_pristine()` error

### ISSUE THREAD

**Issue by mjsteinbaugh** [Bioconductor/DelayedArray#55]
Hi guys, I'm seeing some of my code in [basejump](https://basejump.acidgenomics.com/) error out on bioc-devel due to `is_pristine()` in DelayedArray 0.11.8. Here's the relevant traceback:

```
rowSums(object)
.local(x, rows, cols, na.rm, dim., ...)
DelayedArray:::is_pristine
get(name, envir = asNamespace(pkg), inherits = FALSE)
```

Affected functions in basejump, for reference:

- [`calculateMetrics()`](https://github.com/acidgenomics/basejump/blob/master/R/calculateMetrics-methods.R)
- [`estimateSizeFactors()`](https://github.com/acidgenomics/basejump/blob/master/R/estimateSizeFactors-methods.R)
- [`nonzeroRowsAndCols()`](https://github.com/acidgenomics/basejump/blob/master/R/nonzeroRowsAndCols-methods.R)

Best,
Mike

**Comment by hpages** [comment]
Hi @mjsteinbaugh,

Can you please provide a reproducible example and your sessionInfo()?

Thanks!

**Comment by mjsteinbaugh** [comment]
Sure I'll work on a reprex and get back to you.

**Comment by hpages** [comment]
@mjsteinbaugh Are you planning to follow up on this?  Thx!  H.

**Comment by mjsteinbaugh** [comment]
@hpages Yes I'll work on a reprex this week and get back to you
