### ISSUE TITLE
Implementing sweep() for DelayedArray objects

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/DelayedArray#8]
Hi Hervé,

I thought to implement a `sweep,DelayedArray-method` as `base::sweep()` does not work when `x` is a _DelayedArray_:

```r
suppressPackageStartupMessages(library(DelayedArray))
x <- DelayedArray(matrix(1:10000000, ncol = 1000))
sweep(x, 2, colMeans(x))
#> Error in .DelayedArray_Ops_with_right_vector(.Generic, e1, e2): length of right object is not a divisor of number of rows in left
#>   object
```

In doing so, I realised that `base::sweep()` _almost_ works, it only breaks at the final line:

```r
# https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/base/R/sweep.R#L44
FUN(x, aperm(array(STATS, dims[perm]), order(perm)), ...)
```

i.e. in this case, because `FUN()` (`-`) works when `e1` and `e2` are either both _array_ objects or both _DelayedArray_ objects, but errors if there is one of each type.

I'm thinking of 2 directions I could go in:

1. Changes to `DelayedArray,Ops-method`: Automagic wrapping of `e1` or `e2` in a _DelayedArray_ when one arg is an _array_ and the other is a _DelayedArray_ (and the `e1` and `e2` have conformable dimensions). `base::sweep()` will then work out-of-the-box on for most commonly used `FUN` when `x` is a _DelayedArray_
2. Implement a `sweep,DelayedArray-method`: This will introduce some redundant code from `base::sweep()` but gives more control over how it is implemented. For example, `base::sweep()` creates an intermediate array of the same dimensions as `x`. This intermediate array may be very large, even impossible to store in-memory, in which case it could be written to disk as an _HDF5Array_. Alternatively, as in the above example, this intermediate array may be highly redundant and could be efficiently stored in-memory as an _RleArray_.

What do you think is the best way to go?

**Comment by PeteHaitch** [comment]
I just saw 55c89c4949f65ff53ba2c5f11e01e4f5d4c0ff6e. Thanks, Hervé! Would you mind bumping the version number?

**Comment by hpages** [comment]
Hi Pete @PeteHaitch ,

I added a `"sweep"` method for DelayedArray objects in DelayedArray 0.5.23. It only supports a MARGIN of length 1 for now.

Hopefully that's all you need for now.

Supporting a MARGIN of arbitrary length is a more complicated story and would require enhancing the capabilities of the binary operations of the Ops group. In particular, as you pointed out, these operations would need to accept a DelayedArray object `e1` and an array-like object `e2` where `dim(e2)` is identical to `dim(e1)[MARGIN]` (i.e. `e1` is the "big" array and `e2` is the "small" one), and they would need to be able to replicate the small one to the size of the big one in an efficient manner. I believe that this replication could actually be implemented as a delayed operation itself.

Note that supporting delayed array replication would have its own value per se but it would also probably benefit other delayed operations like `pmax2` and `pmin2`, not just the members of the Ops group. I added this to `DelayedArray/TODO`.

H.

**Comment by PeteHaitch** [comment]
Thanks, Hervé! Indeed, I only need `MARGIN` of length 1 for now. Does it need a version bump to propagate?
