### ISSUE TITLE
DelayedArray Install Failed in R4.0.2

### ISSUE THREAD

**Issue by guodudou** [Bioconductor/DelayedArray#85]
Hello,

I am using macOS Catelina, Bioconductor version 3.11 (BiocManager 1.30.10), R version 4.0.2, and trying to install DelayedArray using BiocManager::install("DelayedArray"), but it shows the following error:

---------------------------------------------------------------------------
Warning messages:
1: multiple methods tables found for ‘mstack’ 
2: multiple methods tables found for ‘which’ 
Warning: replacing previous import ‘S4Vectors::mstack’ by ‘IRanges::mstack’ when loading ‘DelayedArray’
Creating a new generic function for ‘rowsum’ in package ‘DelayedArray’
Creating a new generic function for ‘aperm’ in package ‘DelayedArray’
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  : 
  no definition was found for superclass “DataTable” in the specification of class “DelayedMatrix”
Error: unable to load R code in package ‘DelayedArray’
Execution halted
ERROR: lazy loading failed for package ‘DelayedArray’
* removing ‘/usr/local/lib/R/4.0/site-library/DelayedArray’
* restoring previous ‘/usr/local/lib/R/4.0/site-library/DelayedArray’
-------------------------------------------------------------------------

Do you have any suggestion about how to fix it?
Thank you very much!

**Comment by hpages** [comment]
Hi,

It's very likely that you have a mix of incompatible packages from different versions of Bioconductor. Check this by running `BiocManage::valid()`.

Also please note that Bioconductor 3.11 is no longer supported. We strongly advise to always use the latest Bioconductor release, which is Bioconductor 3.12 at the moment (was released in October 2020). Time to upgrade!

H.

**Comment by guodudou** [comment]
Hello,

Thank you very much for your timely reply and suggestion. I updated R and
Bioconductor to the latest version, and DelayedArray was installed very
well.

Thanks,
Wendy

**Comment by hpages** [comment]
Excellent!
