### ISSUE TITLE
drop() doesn't preserve dimnames in release?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/DelayedArray#86]
Seems like `drop()` on DA's doesn't preserve dimnames in BioC-release:

```r
library(DelayedArray)
x <- DelayedArray(cbind(A=1:10, B=2:11))
x[1,]
## [1] 1 2
```

On BioC-devel, it does the right thing:

```r
library(DelayedArray)
x <- DelayedArray(cbind(A=1:10, B=2:11))
x[1,]
## A B
## 1 2
```

Seems like a simple patch across to BioC-release would suffice.

**Comment by hpages** [comment]
Ah right, forgot to backport commit 8623979c85fff8be8721845981ba1673d6b8ff83 (discussed in issue #78) to the RELEASE_3_12 branch. Should be done now (in DelayedArray 0.16.1).
