### ISSUE TITLE
Benchmarking grouped matrix averaging methods

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/DelayedArray#96]
Wanted to flag this issue here bc I realize there's quite a bit of overlap in many of the these functions between packages.

https://github.com/PeteHaitch/DelayedMatrixStats/issues/82 

**Update**: I've been noticing a higher than expected number of zeros when computing grouped means on sparse DelayedArrays (relative to other similar datasets that were processed using dense base-type matrices). Wondering if this might be related to the point precision.

**Comment by bschilder** [comment]
@hpages could you provide a link to where this benchmarking was done? Or provide a summary here?

**Comment by hpages** [comment]
Not sure. I closed this because it's just a link to an issue that you opened in the DelayedMatrixStats repo, which has been closed since. Happy to reopen if you can reformulate the problem here with a reproducible example + sessionInfo(). Thanks!
