### ISSUE TITLE
Where can i find the old version

### ISSUE THREAD

**Issue by penglu2004** [Bioconductor/DelayedArray#99]
My R version is 3.6.1, so I need the DelayedArray version >= 0.15.14. But the archive is only 0.19.4, where can I find all the old archives. Thanks a lot.

**Comment by lshep** [comment]
If you do `BiocManager::install('DelayedArray')` it should automatically download the appropriate version for your R and Bioconductor. It looks like for R 3.6.1 the Bioconductor version appropriate is 3.10 and DelayedArray version 0.12.3 per the [landing page](http://bioconductor.org/packages/3.10/bioc/html/DelayedArray.html).   To get a version of DelayedArray >=0.15.14 you will need to be using at least Bioconductor 3.12 which carries DelayedArray 0.16.3 but you need at least R 4.0 to use that version.  It is not recommended but you could download the archive from the [Delayed Array Landing Page](https://bioconductor.org/packages/release/bioc/html/DelayedArray.html) and install it manually but this could result in mixed versions of packages and not properly working DelayedArray as the necessary dependencies may not be available and there were a lot of updates in base R between R 3.6 and R >= 4.0
